# Generated by Django 4.2 on 2024-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra'), ('Fu', 'Futblista'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
