# Generated by Django 4.2 on 2024-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('A', 'Agua')], max_length=30),
        ),
    ]
